apiVersion: v1
kind: Service
metadata:
  name: payroll-service
  labels:
    metrics: enabled
spec:
  selector:
    app: payroll-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP