apiVersion: v1
kind: ConfigMap
metadata:
  name: payroll-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payrollService
  SPRING_DATASOURCE_USERNAME: root
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka