fullnameOverride: attendance-service

port: 8084

image:
  repository: satheesh012/attendance-service
  tag: db6b2529b72c7142f0b55b3122002081cca0deac

config:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/attendanceService
  SPRING_DATASOURCE_USERNAME: root
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
  SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: "60000"

secretEnv:
  secretName: mysql-secret
  keys:
    SPRING_DATASOURCE_PASSWORD: SPRING_DATASOURCE_PASSWORD
