apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  labels:
    metrics: enabled
spec:
  selector:
    app: attendance-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP