apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: hrms
data:
  SERVER_PORT: "8088"
  SPRING_APPLICATION_NAME: scheduler-service

  SPRING_MAIL_HOST: smtp.gmail.com
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  CRON_PAYROLL: "*/30 * * * * ?"
  CRON_ATTENDANCE_DAILY: "*/30 * * * * ?"
  CRON_ATTENDANCE_WEEKLY: "*/30 * * * * ?"
  CRON_REMINDERS_LEAVES: "*/30 * * * * ?"

  LOGGING_LEVEL_ORG_SPRING_CLOUD_OPENFEIGN: DEBUG