apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: hrms
  labels:
    metrics: enabled
spec:
  selector:
    app: scheduler-service
  ports:
    - name: http
      port: 8088
      targetPort: 8088
  type: ClusterIP