apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-config
  namespace: hrms
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employeeService
  SPRING_DATASOURCE_USERNAME: root
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka