apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: hrms
  labels:
    metrics: enabled
spec:
  selector:
    app: department-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP