apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        tier: backend
    spec:
      containers:
        - name: notification-service
          image: satheesh012/notification-service:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8087

          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SERVER_PORT

            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_APPLICATION_NAME

            - name: SPRING_MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_MAIL_HOST

            - name: SPRING_MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_MAIL_PORT

            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH

            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY

            - name: LOGGING_LEVEL_COM_TVM_NOTIFICATION
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: LOGGING_LEVEL_COM_TVM_NOTIFICATION

            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_MAIL_USERNAME

            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_MAIL_PASSWORD
                  
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8087
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false