apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  SERVER_PORT: "8087"
  SPRING_APPLICATION_NAME: notification-service

  SPRING_MAIL_HOST: smtp.gmail.com
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
  LOGGING_LEVEL_COM_TVM_NOTIFICATION: DEBUG