apiVersion: v1
kind: Service
metadata:
  name: leave-service
  labels:
    metrics: enabled
spec:
  selector:
    app: leave-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  type: ClusterIP