{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "microservice.fullname" .)) .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: {{ .Values.secret.type | default "Opaque" }}
stringData:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
