apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    metrics: enabled
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ default .Values.port .Values.service.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ include "microservice.fullname" . }}
