apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    metrics: enabled
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP